name: Lint

on:
  push:
    branches: [master, devel]
  pull_request:
    branches: [master, devel]

jobs:
  lint:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: |
          pipx install poetry
      
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
          # cache: 'poetry'
      
      - name: Run poetry install
        run: |
          poetry env use '3.10'
          poetry install

      - name: Check formatting with Black
        run: |
          poetry run black --check --diff --color .

      - name: Run flake8
        run: |
          poetry run flake8
