name: Lint

on:
  push:
    branches: [master, devel]
  pull_request:
    branches: [master, devel]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          # cache: 'poetry'

      - name: Run poetry install
        run: |
          poetry env use '3.10'
          poetry install

      - name: Check formatting with Black
        run: |
          poetry run black --check --diff --color .

      - name: Run flake8
        run: |
          poetry run flake8

      - name: Run isort
        run: |
          poetry run isort --check --diff --color .

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Set up JS requirements
        run: npm install
        working-directory: ./frontend

      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend
